<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DefaultItemExcludes>$(DefaultItemExcludes);BuildHost-net472\**;BuildHost-netcore\**</DefaultItemExcludes>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" Version="9.3.1" />
        <PackageReference Include="Konscious.Security.Cryptography.Argon2" Version="1.3.1" />
        <PackageReference Include="MailKit" Version="4.17.0" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.11" />
        <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.11" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />

        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BazzarOn.Domain\BazzarOn.Domain.csproj" />
        <ProjectReference Include="..\BazzarOn.Application\BazzarOn.Application.csproj" />
    </ItemGroup>

</Project>
 