<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Aggregate Root\" />
      <Folder Include="Events\" />
      <Folder Include="Services\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Shared\BazzarOn.Mediator.Helper\BazzarOn.Mediator.Helper.csproj" />
    </ItemGroup>

</Project>
