<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="10.0.11" />
        <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.12" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BazzarOn.Mediator.Helper\BazzarOn.Mediator.Helper.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>